/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sa.ui;

/**
 *
 * @author Standard
 */
public class FrmCadastroDeCursos extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroDeCursos
     */
    public FrmCadastroDeCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipo = new javax.swing.ButtonGroup();
        pnlCurso = new javax.swing.JPanel();
        lblNomeDoCurso = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblCargaHoraria = new javax.swing.JLabel();
        lblQuantidadeDeHorasAC = new javax.swing.JLabel();
        txtNomeDoCurso = new javax.swing.JTextField();
        txtCargaHoraria = new javax.swing.JTextField();
        txtQuantidadeDeHorasAC = new javax.swing.JTextField();
        rbGraduacao = new javax.swing.JRadioButton();
        rbPosGraduacao = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cursos");
        setMinimumSize(new java.awt.Dimension(500, 230));

        pnlCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));

        lblNomeDoCurso.setText("Nome do Curso:");

        lblTipo.setText("Tipo:");

        lblCargaHoraria.setText("Carga Horária:");

        lblQuantidadeDeHorasAC.setText("Quantidade de Horas AC:");

        grpTipo.add(rbGraduacao);
        rbGraduacao.setText("Graduação");

        grpTipo.add(rbPosGraduacao);
        rbPosGraduacao.setText("Pós-Graduação");

        btnCancelar.setText("Cancelar");

        btnConfirmar.setText("Confirmar");

        javax.swing.GroupLayout pnlCursoLayout = new javax.swing.GroupLayout(pnlCurso);
        pnlCurso.setLayout(pnlCursoLayout);
        pnlCursoLayout.setHorizontalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCursoLayout.createSequentialGroup()
                        .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeDoCurso)
                            .addComponent(lblCargaHoraria)
                            .addComponent(lblQuantidadeDeHorasAC)
                            .addComponent(lblTipo))
                        .addGap(33, 33, 33)
                        .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeDoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addGroup(pnlCursoLayout.createSequentialGroup()
                                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtQuantidadeDeHorasAC, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbGraduacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPosGraduacao))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCursoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        pnlCursoLayout.setVerticalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeDoCurso)
                    .addComponent(txtNomeDoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rbGraduacao)
                    .addComponent(rbPosGraduacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargaHoraria)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeDeHorasAC)
                    .addComponent(txtQuantidadeDeHorasAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup grpTipo;
    private javax.swing.JLabel lblCargaHoraria;
    private javax.swing.JLabel lblNomeDoCurso;
    private javax.swing.JLabel lblQuantidadeDeHorasAC;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlCurso;
    private javax.swing.JRadioButton rbGraduacao;
    private javax.swing.JRadioButton rbPosGraduacao;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtNomeDoCurso;
    private javax.swing.JTextField txtQuantidadeDeHorasAC;
    // End of variables declaration//GEN-END:variables
}
